"""Nationality validation reference for the signup wizard.

Maps lowercase nationality adjectives AND lowercase country names to the canonical
Title-Case nationality adjective stored in signup_records.nationality.
"other" (any case) is the universal fallback → stored as "Other".

Usage::
    from utils.nationality_data import NATIONALITY_LOOKUP
    canonical = NATIONALITY_LOOKUP.get(raw.strip().lower())  # None → invalid
"""

from __future__ import annotations

NATIONALITY_LOOKUP: dict[str, str] = {
    # ── Universal fallback ───────────────────────────────────────────────────
    "other": "Other",

    # ── A ────────────────────────────────────────────────────────────────────
    "afghan":                  "Afghan",
    "afghanistan":             "Afghan",
    "albanian":                "Albanian",
    "albania":                 "Albanian",
    "algerian":                "Algerian",
    "algeria":                 "Algerian",
    "andorran":                "Andorran",
    "andorra":                 "Andorran",
    "angolan":                 "Angolan",
    "angola":                  "Angolan",
    "antiguan":                "Antiguan",
    "antigua":                 "Antiguan",
    "antigua and barbuda":     "Antiguan",
    "argentine":               "Argentine",
    "argentinian":             "Argentine",
    "argentina":               "Argentine",
    "armenian":                "Armenian",
    "armenia":                 "Armenian",
    "australian":              "Australian",
    "australia":               "Australian",
    "austrian":                "Austrian",
    "austria":                 "Austrian",
    "azerbaijani":             "Azerbaijani",
    "azerbaijan":              "Azerbaijani",

    # ── B ────────────────────────────────────────────────────────────────────
    "bahamian":                "Bahamian",
    "bahamas":                 "Bahamian",
    "the bahamas":             "Bahamian",
    "bahraini":                "Bahraini",
    "bahrain":                 "Bahraini",
    "bangladeshi":             "Bangladeshi",
    "bangladesh":              "Bangladeshi",
    "barbadian":               "Barbadian",
    "barbados":                "Barbadian",
    "belarusian":              "Belarusian",
    "belarus":                 "Belarusian",
    "belgian":                 "Belgian",
    "belgium":                 "Belgian",
    "belizean":                "Belizean",
    "belize":                  "Belizean",
    "beninese":                "Beninese",
    "benin":                   "Beninese",
    "bhutanese":               "Bhutanese",
    "bhutan":                  "Bhutanese",
    "bolivian":                "Bolivian",
    "bolivia":                 "Bolivian",
    "bosnian":                 "Bosnian",
    "bosnia":                  "Bosnian",
    "bosnia and herzegovina":  "Bosnian",
    "botswanan":               "Botswanan",
    "botswana":                "Botswanan",
    "brazilian":               "Brazilian",
    "brazil":                  "Brazilian",
    "bruneian":                "Bruneian",
    "brunei":                  "Bruneian",
    "bulgarian":               "Bulgarian",
    "bulgaria":                "Bulgarian",
    "burkinabe":               "Burkinabe",
    "burkina faso":            "Burkinabe",
    "burmese":                 "Burmese",
    "myanmar":                 "Burmese",
    "burundian":               "Burundian",
    "burundi":                 "Burundian",

    # ── C ────────────────────────────────────────────────────────────────────
    "cambodian":               "Cambodian",
    "cambodia":                "Cambodian",
    "cameroonian":             "Cameroonian",
    "cameroon":                "Cameroonian",
    "canadian":                "Canadian",
    "canada":                  "Canadian",
    "cape verdean":            "Cape Verdean",
    "cape verde":              "Cape Verdean",
    "central african":         "Central African",
    "central african republic": "Central African",
    "chadian":                 "Chadian",
    "chad":                    "Chadian",
    "chilean":                 "Chilean",
    "chile":                   "Chilean",
    "chinese":                 "Chinese",
    "china":                   "Chinese",
    "colombian":               "Colombian",
    "colombia":                "Colombian",
    "comorian":                "Comorian",
    "comoros":                 "Comorian",
    "congolese":               "Congolese",
    "congo":                   "Congolese",
    "democratic republic of the congo": "Congolese",
    "republic of the congo":   "Congolese",
    "costa rican":             "Costa Rican",
    "costa rica":              "Costa Rican",
    "ivorian":                 "Ivorian",
    "ivory coast":             "Ivorian",
    "cote d'ivoire":           "Ivorian",
    "croat":                   "Croatian",
    "croatian":                "Croatian",
    "croatia":                 "Croatian",
    "cuban":                   "Cuban",
    "cuba":                    "Cuban",
    "cypriot":                 "Cypriot",
    "cyprus":                  "Cypriot",
    "czech":                   "Czech",
    "czechia":                 "Czech",
    "czech republic":          "Czech",

    # ── D ────────────────────────────────────────────────────────────────────
    "danish":                  "Danish",
    "denmark":                 "Danish",
    "dane":                    "Danish",
    "djiboutian":              "Djiboutian",
    "djibouti":                "Djiboutian",
    "dominican":               "Dominican",
    "dominica":                "Dominican",
    "dominican republic":      "Dominican",

    # ── E ────────────────────────────────────────────────────────────────────
    "ecuadorian":              "Ecuadorian",
    "ecuador":                 "Ecuadorian",
    "egyptian":                "Egyptian",
    "egypt":                   "Egyptian",
    "salvadoran":              "Salvadoran",
    "el salvador":             "Salvadoran",
    "equatorial guinean":      "Equatorial Guinean",
    "equatorial guinea":       "Equatorial Guinean",
    "eritrean":                "Eritrean",
    "eritrea":                 "Eritrean",
    "estonian":                "Estonian",
    "estonia":                 "Estonian",
    "eswatini":                "Swazi",
    "swazi":                   "Swazi",
    "swaziland":               "Swazi",
    "ethiopian":               "Ethiopian",
    "ethiopia":                "Ethiopian",

    # ── F ────────────────────────────────────────────────────────────────────
    "fijian":                  "Fijian",
    "fiji":                    "Fijian",
    "finnish":                 "Finnish",
    "finland":                 "Finnish",
    "finn":                    "Finnish",
    "french":                  "French",
    "france":                  "French",

    # ── G ────────────────────────────────────────────────────────────────────
    "gabonese":                "Gabonese",
    "gabon":                   "Gabonese",
    "gambian":                 "Gambian",
    "gambia":                  "Gambian",
    "the gambia":              "Gambian",
    "georgian":                "Georgian",
    "georgia":                 "Georgian",
    "german":                  "German",
    "germany":                 "German",
    "ghanaian":                "Ghanaian",
    "ghana":                   "Ghanaian",
    "greek":                   "Greek",
    "greece":                  "Greek",
    "grenadian":               "Grenadian",
    "grenada":                 "Grenadian",
    "guatemalan":              "Guatemalan",
    "guatemala":               "Guatemalan",
    "guinean":                 "Guinean",
    "guinea":                  "Guinean",
    "guinea-bissauan":         "Guinean",
    "guinea-bissau":           "Guinean",
    "guyanese":                "Guyanese",
    "guyana":                  "Guyanese",

    # ── H ────────────────────────────────────────────────────────────────────
    "haitian":                 "Haitian",
    "haiti":                   "Haitian",
    "honduran":                "Honduran",
    "honduras":                "Honduran",
    "hungarian":               "Hungarian",
    "hungary":                 "Hungarian",

    # ── I ────────────────────────────────────────────────────────────────────
    "icelandic":               "Icelandic",
    "iceland":                 "Icelandic",
    "indian":                  "Indian",
    "india":                   "Indian",
    "indonesian":              "Indonesian",
    "indonesia":               "Indonesian",
    "iranian":                 "Iranian",
    "iran":                    "Iranian",
    "iraqi":                   "Iraqi",
    "iraq":                    "Iraqi",
    "irish":                   "Irish",
    "ireland":                 "Irish",
    "republic of ireland":     "Irish",
    "israeli":                 "Israeli",
    "israel":                  "Israeli",
    "italian":                 "Italian",
    "italy":                   "Italian",

    # ── J ────────────────────────────────────────────────────────────────────
    "jamaican":                "Jamaican",
    "jamaica":                 "Jamaican",
    "japanese":                "Japanese",
    "japan":                   "Japanese",
    "jordanian":               "Jordanian",
    "jordan":                  "Jordanian",

    # ── K ────────────────────────────────────────────────────────────────────
    "kazakhstani":             "Kazakhstani",
    "kazakh":                  "Kazakhstani",
    "kazakhstan":              "Kazakhstani",
    "kenyan":                  "Kenyan",
    "kenya":                   "Kenyan",
    "i-kiribati":              "I-Kiribati",
    "kiribati":                "I-Kiribati",
    "north korean":            "North Korean",
    "north korea":             "North Korean",
    "south korean":            "South Korean",
    "south korea":             "South Korean",
    "korean":                  "South Korean",
    "kuwaiti":                 "Kuwaiti",
    "kuwait":                  "Kuwaiti",
    "kyrgyz":                  "Kyrgyz",
    "kyrgyzstan":              "Kyrgyz",

    # ── L ────────────────────────────────────────────────────────────────────
    "laotian":                 "Laotian",
    "lao":                     "Laotian",
    "laos":                    "Laotian",
    "latvian":                 "Latvian",
    "latvia":                  "Latvian",
    "lebanese":                "Lebanese",
    "lebanon":                 "Lebanese",
    "basotho":                 "Basotho",
    "lesotho":                 "Basotho",
    "liberian":                "Liberian",
    "liberia":                 "Liberian",
    "libyan":                  "Libyan",
    "libya":                   "Libyan",
    "liechtensteiner":         "Liechtensteiner",
    "liechtenstein":           "Liechtensteiner",
    "lithuanian":              "Lithuanian",
    "lithuania":               "Lithuanian",
    "luxembourger":            "Luxembourger",
    "luxembourg":              "Luxembourger",

    # ── M ────────────────────────────────────────────────────────────────────
    "malagasy":                "Malagasy",
    "madagascar":              "Malagasy",
    "malawian":                "Malawian",
    "malawi":                  "Malawian",
    "malaysian":               "Malaysian",
    "malaysia":                "Malaysian",
    "maldivian":               "Maldivian",
    "maldives":                "Maldivian",
    "malian":                  "Malian",
    "mali":                    "Malian",
    "maltese":                 "Maltese",
    "malta":                   "Maltese",
    "marshallese":             "Marshallese",
    "marshall islands":        "Marshallese",
    "mauritanian":             "Mauritanian",
    "mauritania":              "Mauritanian",
    "mauritian":               "Mauritian",
    "mauritius":               "Mauritian",
    "mexican":                 "Mexican",
    "mexico":                  "Mexican",
    "micronesian":             "Micronesian",
    "micronesia":              "Micronesian",
    "moldovan":                "Moldovan",
    "moldova":                 "Moldovan",
    "monegasque":              "Monegasque",
    "monaco":                  "Monegasque",
    "mongolian":               "Mongolian",
    "mongolia":                "Mongolian",
    "montenegrin":             "Montenegrin",
    "montenegro":              "Montenegrin",
    "moroccan":                "Moroccan",
    "morocco":                 "Moroccan",
    "mozambican":              "Mozambican",
    "mozambique":              "Mozambican",

    # ── N ────────────────────────────────────────────────────────────────────
    "namibian":                "Namibian",
    "namibia":                 "Namibian",
    "nauruan":                 "Nauruan",
    "nauru":                   "Nauruan",
    "nepali":                  "Nepali",
    "nepalese":                "Nepali",
    "nepal":                   "Nepali",
    "dutch":                   "Dutch",
    "netherlands":             "Dutch",
    "the netherlands":         "Dutch",
    "new zealander":           "New Zealander",
    "new zealand":             "New Zealander",
    "nicaraguan":              "Nicaraguan",
    "nicaragua":               "Nicaraguan",
    "nigerien":                "Nigerien",
    "niger":                   "Nigerien",
    "nigerian":                "Nigerian",
    "nigeria":                 "Nigerian",
    "macedonian":              "Macedonian",
    "north macedonian":        "Macedonian",
    "north macedonia":         "Macedonian",
    "norwegian":               "Norwegian",
    "norway":                  "Norwegian",

    # ── O ────────────────────────────────────────────────────────────────────
    "omani":                   "Omani",
    "oman":                    "Omani",

    # ── P ────────────────────────────────────────────────────────────────────
    "pakistani":               "Pakistani",
    "pakistan":                "Pakistani",
    "palauan":                 "Palauan",
    "palau":                   "Palauan",
    "panamanian":              "Panamanian",
    "panama":                  "Panamanian",
    "papua new guinean":       "Papua New Guinean",
    "papua new guinea":        "Papua New Guinean",
    "paraguayan":              "Paraguayan",
    "paraguay":                "Paraguayan",
    "peruvian":                "Peruvian",
    "peru":                    "Peruvian",
    "filipino":                "Filipino",
    "philippine":              "Filipino",
    "philippines":             "Filipino",
    "polish":                  "Polish",
    "poland":                  "Polish",
    "pole":                    "Polish",
    "portuguese":              "Portuguese",
    "portugal":                "Portuguese",

    # ── Q ────────────────────────────────────────────────────────────────────
    "qatari":                  "Qatari",
    "qatar":                   "Qatari",

    # ── R ────────────────────────────────────────────────────────────────────
    "romanian":                "Romanian",
    "romania":                 "Romanian",
    "russian":                 "Russian",
    "russia":                  "Russian",
    "rwandan":                 "Rwandan",
    "rwanda":                  "Rwandan",

    # ── S ────────────────────────────────────────────────────────────────────
    "saint kittsian":          "Saint Kittsian",
    "saint kitts and nevis":   "Saint Kittsian",
    "saint lucian":            "Saint Lucian",
    "saint lucia":             "Saint Lucian",
    "saint vincentian":        "Saint Vincentian",
    "saint vincent and the grenadines": "Saint Vincentian",
    "samoan":                  "Samoan",
    "samoa":                   "Samoan",
    "san marinese":            "San Marinese",
    "san marino":              "San Marinese",
    "sao tomean":              "Sao Tomean",
    "sao tome and principe":   "Sao Tomean",
    "saudi":                   "Saudi",
    "saudi arabian":           "Saudi",
    "saudi arabia":            "Saudi",
    "senegalese":              "Senegalese",
    "senegal":                 "Senegalese",
    "serbian":                 "Serbian",
    "serbia":                  "Serbian",
    "seychellois":             "Seychellois",
    "seychelles":              "Seychellois",
    "sierra leonean":          "Sierra Leonean",
    "sierra leone":            "Sierra Leonean",
    "singaporean":             "Singaporean",
    "singapore":               "Singaporean",
    "slovak":                  "Slovak",
    "slovakia":                "Slovak",
    "slovenian":               "Slovenian",
    "slovenia":                "Slovenian",
    "solomon islander":        "Solomon Islander",
    "solomon islands":         "Solomon Islander",
    "somali":                  "Somali",
    "somalia":                 "Somali",
    "south african":           "South African",
    "south africa":            "South African",
    "south sudanese":          "South Sudanese",
    "south sudan":             "South Sudanese",
    "spanish":                 "Spanish",
    "spain":                   "Spanish",
    "spaniard":                "Spanish",
    "sri lankan":              "Sri Lankan",
    "sri lanka":               "Sri Lankan",
    "sudanese":                "Sudanese",
    "sudan":                   "Sudanese",
    "surinamese":              "Surinamese",
    "suriname":                "Surinamese",
    "swedish":                 "Swedish",
    "sweden":                  "Swedish",
    "swede":                   "Swedish",
    "swiss":                   "Swiss",
    "switzerland":             "Swiss",
    "syrian":                  "Syrian",
    "syria":                   "Syrian",

    # ── T ────────────────────────────────────────────────────────────────────
    "taiwanese":               "Taiwanese",
    "taiwan":                  "Taiwanese",
    "tajik":                   "Tajik",
    "tajikistan":              "Tajik",
    "tanzanian":               "Tanzanian",
    "tanzania":                "Tanzanian",
    "thai":                    "Thai",
    "thailand":                "Thai",
    "timorese":                "Timorese",
    "east timorese":           "Timorese",
    "timor-leste":             "Timorese",
    "east timor":              "Timorese",
    "togolese":                "Togolese",
    "togo":                    "Togolese",
    "tongan":                  "Tongan",
    "tonga":                   "Tongan",
    "trinidadian":             "Trinidadian",
    "trinidad and tobago":     "Trinidadian",
    "trinidadian and tobagonian": "Trinidadian",
    "tunisian":                "Tunisian",
    "tunisia":                 "Tunisian",
    "turkish":                 "Turkish",
    "turkey":                  "Turkish",
    "turkiye":                 "Turkish",
    "turk":                    "Turkish",
    "turkmen":                 "Turkmen",
    "turkmenistan":            "Turkmen",
    "tuvaluan":                "Tuvaluan",
    "tuvalu":                  "Tuvaluan",

    # ── U ────────────────────────────────────────────────────────────────────
    "ugandan":                 "Ugandan",
    "uganda":                  "Ugandan",
    "ukrainian":               "Ukrainian",
    "ukraine":                 "Ukrainian",
    "emirati":                 "Emirati",
    "uae":                     "Emirati",
    "united arab emirates":    "Emirati",
    "british":                 "British",
    "united kingdom":          "British",
    "english":                 "British",
    "scottish":                "British",
    "welsh":                   "British",
    "northern irish":          "British",
    "england":                 "British",
    "scotland":                "British",
    "wales":                   "British",
    "northern ireland":        "British",
    "american":                "American",
    "usa":                     "American",
    "united states":           "American",
    "united states of america": "American",
    "uruguayan":               "Uruguayan",
    "uruguay":                 "Uruguayan",
    "uzbek":                   "Uzbek",
    "uzbekistan":              "Uzbek",

    # ── V ────────────────────────────────────────────────────────────────────
    "ni-vanuatu":              "Ni-Vanuatu",
    "vanuatuan":               "Ni-Vanuatu",
    "vanuatu":                 "Ni-Vanuatu",
    "venezuelan":              "Venezuelan",
    "venezuela":               "Venezuelan",
    "vietnamese":              "Vietnamese",
    "vietnam":                 "Vietnamese",
    "viet nam":                "Vietnamese",

    # ── Y ────────────────────────────────────────────────────────────────────
    "yemeni":                  "Yemeni",
    "yemen":                   "Yemeni",

    # ── Z ────────────────────────────────────────────────────────────────────
    "zambian":                 "Zambian",
    "zambia":                  "Zambian",
    "zimbabwean":              "Zimbabwean",
    "zimbabwe":                "Zimbabwean",
}
